//Tshirt RobotContainer

package frc.robot;

import frc.robot.commands.*;
import frc.robot.subsystems.*;
<<<<<<< HEAD:TshirtRobotCommandBasedCode/src/main/java/frc/robot/RobotContainer.java
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
//import edu.wpi.first.wpilibj2.command.Command.InterruptionBehavior;
=======
//import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
//import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command.InterruptionBehavior;
>>>>>>> df2b90c50192b6f713a735fcfb4c15b3e97b10cb:TankCommandBased/src/main/java/frc/robot/RobotContainer.java

import edu.wpi.first.wpilibj2.command.Command;
<<<<<<< HEAD:TshirtRobotCommandBasedCode/src/main/java/frc/robot/RobotContainer.java
//import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj.Joystick;
//import frc.robot.subsystems.*;
=======
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj.XboxController;
import frc.robot.subsystems.*;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
>>>>>>> df2b90c50192b6f713a735fcfb4c15b3e97b10cb:TankCommandBased/src/main/java/frc/robot/RobotContainer.java


public class RobotContainer {

  private static RobotContainer m_robotContainer = new RobotContainer();
  public final Drivetrain m_drivetrain = new Drivetrain();
  private final Joystick joystick1 = new Joystick(0);

<<<<<<< HEAD:TshirtRobotCommandBasedCode/src/main/java/frc/robot/RobotContainer.java
=======
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
// The robot's subsystems
    public final Drivetrain m_drivetrain = new Drivetrain();

// Joysticks
private final XboxController xboxController1 = new XboxController(0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  
  // A chooser for autonomous commands
>>>>>>> df2b90c50192b6f713a735fcfb4c15b3e97b10cb:TankCommandBased/src/main/java/frc/robot/RobotContainer.java
  SendableChooser<Command> m_chooser = new SendableChooser<>();

 
  private RobotContainer() {
 
    SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
<<<<<<< HEAD:TshirtRobotCommandBasedCode/src/main/java/frc/robot/RobotContainer.java
  
    configureButtonBindings();

    
=======
    SmartDashboard.putData("OperatorDriven", new OperatorDriven( m_drivetrain ));

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Configure the button bindings
    configureButtonBindings();

    // Configure default commands
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

    // Configure autonomous sendable chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

>>>>>>> df2b90c50192b6f713a735fcfb4c15b3e97b10cb:TankCommandBased/src/main/java/frc/robot/RobotContainer.java
    m_chooser.setDefaultOption("Autonomous Command", new AutonomousCommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    SmartDashboard.putData("Auto Mode", m_chooser);
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings.  Buttons can be created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
// Create some buttons


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
  }

<<<<<<< HEAD:TshirtRobotCommandBasedCode/src/main/java/frc/robot/RobotContainer.java
public Joystick getJoystick1() {
        return joystick1;
=======
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
public XboxController getXboxController1() {
      return xboxController1;
>>>>>>> df2b90c50192b6f713a735fcfb4c15b3e97b10cb:TankCommandBased/src/main/java/frc/robot/RobotContainer.java
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
  */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }
  

}

